import streamlit as st
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import tempfile


def generate_report():

    styles = getSampleStyleSheet()

    temp_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf"
    )

    doc = SimpleDocTemplate(
        temp_file.name,
        pagesize=letter
    )

    story = []

    story.append(
        Paragraph("<b>Dharti AI Farm Report</b>", styles["Title"])
    )

    story.append(
        Paragraph("Crop Recommendation: Rice", styles["BodyText"])
    )

    story.append(
        Paragraph("Confidence: 98%", styles["BodyText"])
    )

    story.append(
        Paragraph("Climate Score: 80/100", styles["BodyText"])
    )

    story.append(
        Paragraph("Weather: 31°C | 52% Humidity", styles["BodyText"])
    )

    story.append(
        Paragraph("Generated by Dharti AI", styles["Italic"])
    )

    doc.build(story)

    return temp_file.name


def show_report():

    st.title("📄 Reports")

    st.write("Generate a professional farm report.")

    if st.button("📥 Generate Report"):

        pdf = generate_report()

        with open(pdf, "rb") as f:

            st.download_button(
                "⬇ Download PDF",
                f,
                file_name="DhartiAI_Report.pdf",
                mime="application/pdf"
            )